server:
  port: 8088
  servlet:
    session:
      timeout: 1800s

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 3600s
  main:
    banner-mode: console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/springboot2019?serverTimezone=GMT%2b8
    username: root
    password: 970512
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  path: /base-web-log

# 应用信息
app:
  app-name: app
  app-host: http://app.com
  allow-generate-api: true
  allow-cross-domain-access: true
  # 开发dev 测试test  生产 master
  env: dev